<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * bulk_enrollment enrolment plugin.
 *
 * This plugin lets the user specify a "bulk_enrollment" containing enrolment information.
 * On a regular cron cycle, the specified file is parsed and then deleted.
 *
 *
 * @package    enrol_bulk_enrollment
 * @copyright  2021 World University of Bangladesh (CIS)
 * @license    https://license.elearning.com.bd/ GNU GPL v3 or later
 * @author     CIS (https://cis.com/)
 * @author     Farjan Hasan <farjan@wub.edu.bd>
 */

defined('MOODLE_INTERNAL') || die();


class enrol_bulk_enrollment extends enrol_plugin {

    public function allow_manage(stdClass $instance) {
        // Simply making this function return true will render the edit enrolment action in the participants list if the user has the 'enrol/pluginname:manage' capability.
        return true;
    }

    public function allow_unenrol(stdClass $instance) {
        // Simply making this function return true will render the unenrolment action in the participants list if the user has the 'enrol/pluginname:unenrol' capability.
        return true;
    }

    public function allow_enrol(stdClass $instance){
        return false;
        //return parent::allow_enrol($instance); // TODO: Change the autogenerated stub
    }

}

/*function enrol_bulk_enrollment_extend_navigation(global_navigation $navigation){
    if (!has_capability('moodle/site:config', context_system::instance())){
        return;
    }

    $main_node = $navigation->add(get_string('pluginname','enrol_bulk_enrollment'),'/enrol/bulk_enrolment/');
    $main_node->nodetype = 1;
    $main_node->collapse = false;
    $main_node->forceopen = true;
    $main_node->isexpandable = false;
    $main_node->showinflatnavigation = true;
    $navigation->add_node($main_node);
}*/